# Generated by Django 4.1.6 on 2023-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='')),
                ('full_name', models.TextField(default='', max_length=100)),
                ('email_id', models.EmailField(default='', max_length=100)),
                ('mobile_no', models.IntegerField(default=0)),
                ('department_name', models.TextField(default='', max_length=100)),
                ('dateofbirth', models.DateField(default='')),
                ('dateofjoin', models.DateField(default='')),
                ('salary', models.IntegerField(default=0)),
                ('gender', models.TextField(default='', max_length=15)),
                ('role', models.TextField(default='', max_length='50')),
            ],
        ),
    ]
