# Generated by Django 4.1.6 on 2023-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0003_leavemanager_taskmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='task_detail',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
