# Generated by Django 4.1.6 on 2023-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_taskmanager_task_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='status',
            field=models.TextField(default='Remaining', max_length=50),
        ),
    ]
