# Generated by Django 4.1.6 on 2023-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0005_taskmanager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_img',
            field=models.ImageField(upload_to='profile_img'),
        ),
    ]
