# Generated by Django 4.1.6 on 2023-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_profiles_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanager',
            name='status',
            field=models.TextField(default='In Waiting', max_length=50),
        ),
    ]
