# Generated by Django 4.1.6 on 2023-02-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0009_attendacemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendacemanager',
            name='attendance_desc',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='11:54:39'),
        ),
    ]
