# Generated by Django 4.1.6 on 2023-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0010_attendacemanager_attendance_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='address',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='12:00:47'),
        ),
    ]
