# Generated by Django 4.1.6 on 2023-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0011_profiles_address_alter_attendacemanager_arrival_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemanager',
            old_name='leave_reasion',
            new_name='leave_type',
        ),
        migrations.AddField(
            model_name='leavemanager',
            name='leave_reason',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='22:01:19'),
        ),
    ]
