# Generated by Django 4.1.6 on 2023-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0012_rename_leave_reasion_leavemanager_leave_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.TextField(default='', max_length=50)),
                ('emp_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default=0)),
                ('months', models.TextField(default='', max_length=50)),
                ('gross_salary', models.IntegerField(default=0)),
                ('PF', models.IntegerField(default=0)),
                ('PT', models.IntegerField(default=0)),
                ('gross_deduct', models.IntegerField(default=0)),
                ('Net', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='22:48:44'),
        ),
    ]
