# Generated by Django 4.1.6 on 2023-02-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0013_roles_salarytable_taskmanager_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytable',
            name='status',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='22:50:20'),
        ),
    ]
