# Generated by Django 4.1.7 on 2023-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0014_salarytable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='13:51:43'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.TextField(default='', max_length=50),
        ),
    ]
