# Generated by Django 4.1.7 on 2023-03-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0015_departmentlist_alter_attendacemanager_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_app', models.TextField(default='In Waiting', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='09:01:28'),
        ),
    ]
