# Generated by Django 4.1.7 on 2023-03-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0016_leavesdata_alter_attendacemanager_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='09:03:52'),
        ),
        migrations.RemoveField(
            model_name='leavemanager',
            name='status',
        ),
        migrations.AddField(
            model_name='leavemanager',
            name='status',
            field=models.ManyToManyField(to='Mainpage.leavesdata'),
        ),
    ]
