# Generated by Django 4.1.7 on 2023-03-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0017_alter_attendacemanager_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='09:13:42'),
        ),
        migrations.RemoveField(
            model_name='leavemanager',
            name='status',
        ),
        migrations.DeleteModel(
            name='LeavesData',
        ),
        migrations.AddField(
            model_name='leavemanager',
            name='status',
            field=models.TextField(choices=[('In Waiting', 'In Waiting'), ('Approved', 'Approved')], default='In Waiting', max_length=30),
        ),
    ]
