# Generated by Django 4.1.6 on 2023-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0018_alter_attendacemanager_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='22:15:16'),
        ),
        migrations.AlterField(
            model_name='leavemanager',
            name='status',
            field=models.TextField(choices=[('In Waiting', 'In Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='In Waiting', max_length=30),
        ),
    ]
