# Generated by Django 4.1.7 on 2023-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0019_alter_attendacemanager_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='17:13:15'),
        ),
        migrations.AlterField(
            model_name='salarytable',
            name='status',
            field=models.TextField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=30),
        ),
    ]
