# Generated by Django 4.1.6 on 2023-03-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0020_alter_attendacemanager_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendacemanager',
            name='username',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='leavemanager',
            name='username',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roles',
            name='username',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='22:26:52'),
        ),
    ]
