# Generated by Django 4.1.7 on 2023-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0022_taskmanager_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='department_name',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='13:54:48'),
        ),
    ]
