# Generated by Django 4.1.7 on 2023-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0023_roles_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytable',
            name='username',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendacemanager',
            name='arrival_time',
            field=models.TimeField(default='14:42:48'),
        ),
    ]
